"""add author_id on instruction

Revision ID: 180dcf671721
Revises: 4739a29c3bba
Create Date: 2024-04-24 20:37:30.446309

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '180dcf671721'
down_revision = '4739a29c3bba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Instruction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'User', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Instruction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
