"""change ingredient and the relation composition

Revision ID: 631d3a6c03c5
Revises: 0e52461c0957
Create Date: 2024-05-04 18:30:08.497821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '631d3a6c03c5'
down_revision = '0e52461c0957'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredient', sa.String(length=40), nullable=False))
        batch_op.add_column(sa.Column('calories_per_gram', sa.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('fat_per_gram', sa.DECIMAL(precision=10, scale=2), nullable=True))
        batch_op.drop_column('ingredient_unit')
        batch_op.drop_column('ingredient_name')
        batch_op.drop_column('fat_per_unit')
        batch_op.drop_column('calories_per_unit')

    with op.batch_alter_table('Recipe_ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Recipe_ingredient', schema=None) as batch_op:
        batch_op.drop_column('amount')

    with op.batch_alter_table('Ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories_per_unit', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fat_per_unit', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('ingredient_name', sa.VARCHAR(length=40), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('ingredient_unit', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
        batch_op.drop_column('fat_per_gram')
        batch_op.drop_column('calories_per_gram')
        batch_op.drop_column('ingredient')

    # ### end Alembic commands ###
