from .recipe import blp as recipes_blueprint
from .user import blp as users_blueprint
from .user_social import blp as user_socials_blueprint
from .like import blp as likes_blueprint
from .rate import blp as rates_blueprint
from .comment import blp as comments_blueprint
from .feed import blp as feeds_blueprint
from .following import blp as following_blueprint
from .collection import blp as collentions_blueprint
