"""add nutriscore

Revision ID: 1782683a6375
Revises: 180dcf671721
Create Date: 2024-04-28 17:38:50.001221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1782683a6375'
down_revision = '180dcf671721'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nutriscore', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Recipe', schema=None) as batch_op:
        batch_op.drop_column('nutriscore')

    # ### end Alembic commands ###
