"""add new_password column on user for placeholder if new password assigned

Revision ID: f3a98b8e2e8c
Revises: 6516bd5d8d95
Create Date: 2024-04-22 22:22:30.366641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f3a98b8e2e8c'
down_revision = '6516bd5d8d95'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_password', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('new_password')

    # ### end Alembic commands ###
