"""add view_count on user and recipe

Revision ID: de6fc10ec169
Revises: 051fdcaff5a0
Create Date: 2024-04-19 14:42:43.053192

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de6fc10ec169'
down_revision = '051fdcaff5a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('view_count', sa.Integer(), nullable=True))

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('view_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('view_count')

    with op.batch_alter_table('Recipe', schema=None) as batch_op:
        batch_op.drop_column('view_count')

    # ### end Alembic commands ###
