"""change phone column to user model

Revision ID: eebbf5f5dce7
Revises: f3a98b8e2e8c
Create Date: 2024-04-24 13:39:54.864911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eebbf5f5dce7'
down_revision = 'f3a98b8e2e8c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Socials', schema=None) as batch_op:
        batch_op.drop_column('phone')

    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('User', schema=None) as batch_op:
        batch_op.drop_column('phone')

    with op.batch_alter_table('Socials', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=255), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
