"""change recipe title to unique

Revision ID: 54620f037705
Revises: 541857c81397
Create Date: 2024-04-30 09:34:51.360582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54620f037705'
down_revision = '541857c81397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Recipe', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['title'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Recipe', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
