"""connect instruction into recipe directly

Revision ID: e4b42b336d05
Revises: 1782683a6375
Create Date: 2024-04-28 21:42:18.392772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e4b42b336d05'
down_revision = '1782683a6375'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Recipe_instruction')
    with op.batch_alter_table('Instruction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipe_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('Instruction_order_key', type_='unique')
        batch_op.create_foreign_key(None, 'Recipe', ['recipe_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Instruction', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('Instruction_order_key', ['order'])
        batch_op.drop_column('recipe_id')

    op.create_table('Recipe_instruction',
    sa.Column('recipe_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('instruction_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['instruction_id'], ['Instruction.id'], name='Recipe_instruction_instruction_id_fkey'),
    sa.ForeignKeyConstraint(['recipe_id'], ['Recipe.id'], name='Recipe_instruction_recipe_id_fkey'),
    sa.PrimaryKeyConstraint('recipe_id', 'instruction_id', name='Recipe_instruction_pkey')
    )
    # ### end Alembic commands ###
