"""change type of columns in recipe

Revision ID: ee46e593edbb
Revises: e4b42b336d05
Create Date: 2024-04-28 21:49:59.516402

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ee46e593edbb"
down_revision = "e4b42b336d05"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Recipe", schema=None) as batch_op:
        batch_op.alter_column(
            "cooktime",
            type_=sa.Integer,
            using="cooktime::integer",  # Explicit conversion using the USING clause
        )

        batch_op.alter_column(
            "budget",
            existing_type=sa.NUMERIC(precision=10, scale=2),
            type_=sa.String(length=20),
            existing_nullable=False,
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("Recipe", schema=None) as batch_op:
        batch_op.alter_column(
            "budget",
            existing_type=sa.String(length=20),
            type_=sa.NUMERIC(precision=10, scale=2),
            existing_nullable=False,
        )
        batch_op.alter_column(
            "cooktime",
            existing_type=sa.Integer(),
            type_=sa.VARCHAR(length=20),
            existing_nullable=False,
        )

    # ### end Alembic commands ###
