"""changing ingredient

Revision ID: 4483d0eeb6da
Revises: 4e77bbff4351
Create Date: 2024-05-04 20:38:27.740133

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4483d0eeb6da'
down_revision = '4e77bbff4351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wrappers_fdw_stats')
    with op.batch_alter_table('Ingredient', schema=None) as batch_op:
        batch_op.drop_column('fat_per_gram')
        batch_op.drop_column('calories_per_gram')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('calories_per_gram', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('fat_per_gram', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=True))

    op.create_table('wrappers_fdw_stats',
    sa.Column('fdw_name', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('create_times', sa.BIGINT(), autoincrement=False, nullable=True, comment='Total number of times the FDW instacne has been created'),
    sa.Column('rows_in', sa.BIGINT(), autoincrement=False, nullable=True, comment='Total rows input from origin'),
    sa.Column('rows_out', sa.BIGINT(), autoincrement=False, nullable=True, comment='Total rows output to Postgres'),
    sa.Column('bytes_in', sa.BIGINT(), autoincrement=False, nullable=True, comment='Total bytes input from origin'),
    sa.Column('bytes_out', sa.BIGINT(), autoincrement=False, nullable=True, comment='Total bytes output to Postgres'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True, comment='Metadata specific for the FDW'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("timezone('utc'::text, now())"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('fdw_name', name='wrappers_fdw_stats_pkey'),
    comment='Wrappers Foreign Data Wrapper statistics'
    )
    # ### end Alembic commands ###
