"""change ingredient into text with no limit

Revision ID: 18c14b0d6ab3
Revises: 13f6f968b6c4
Create Date: 2024-05-10 19:45:17.895122

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18c14b0d6ab3'
down_revision = '13f6f968b6c4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Ingredient', schema=None) as batch_op:
        batch_op.alter_column('ingredient',
               existing_type=sa.VARCHAR(length=40),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Ingredient', schema=None) as batch_op:
        batch_op.alter_column('ingredient',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=40),
               existing_nullable=False)

    # ### end Alembic commands ###
